### PR TITLE
Added CallExpression support

### PR DESCRIPTION
**Pull request by Andarist**
Extension-less filename sounds like a reasonable default (can be treated as convention) for:
```js
// adjustHue.flow.js
// ...
export default curry(adjustHue)
```

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
This doesn't actually work for your example. The type of the value returned by `curry` is not the same as the type used as an input to `curry`.  Ideally we'd provide some way of customising this, but for now the better approach is probably to do something like:

```js
const curriedAdjustHue: (a: string) => string = curry(adjustHue);
export default curriedAdjustHue;
```

**Comment by Andarist** [comment]
You are right ofc, didnt check my PR properly.

Intention behind the PR is to allow having files containing
```js
// adjustHue.flow.js
// ...
export default curry(adjustHue)
```
instead of splitting this export into 2 lines - which is required by the library right now:
```js
// adjustHue.flow.js
// ...
const curriedAdjustHue = curry(adjustHue)
export default curriedAdjustHue
```

Types remain the same, semantics remain the same. The only difference is how the code is structured.

I believe it is very much possible to support also the first option, it just needs more work.

**Comment by ForbesLindesay** [comment]
The difference is that with:

```js
const curriedAdjustHue: (a: string) => string = curry(adjustHue);
export default curriedAdjustHue;
```

we are explicitly specifying the type of the variable `curriedAdjustHue`.  This works because it means that tsgen doesn't even look at what value is being assigned to that variable.  The nice thing is that flow will verify that the type we have defined is correct.

To do this automatically, we would need to either plug into flow's inference to find out what type the expression has (possible, but slow and probably a fairly big change to lots of stuff) or do much more complete inference ourselves (resolve any generics in the `curry` function etc.`)

**Comment by ForbesLindesay** [comment]
For the example of [curry](https://github.com/styled-components/polished/blob/923b05a0c48e4ee49f085122c9b3a25a66b346ae/src/internalHelpers/_curry.js) this would mean figuring out the types of the parameters, resolving which of the overloaded methods is being called, matching up the parameters to resolve the types of each generic parameter, then plugging those generic types into the return type of the selected overload of the function being called.

**Pull request closed without merging**
